version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - app.env
      - smtp.env
    ports:
      - "8001:8001"
    volumes:
      - ./data/auth-app/images:/app/images

  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgres