basePath: /api/v1/
definitions:
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.loginSampleResponse200:
    properties:
      message:
        example: User Logged in successfully
        type: string
      status:
        example: success
        type: string
      statusCode:
        example: 200
        type: integer
      token:
        example: b6d4a7e1d2d841a1afe874a2a5c15d8b
        type: string
    type: object
  handlers.loginSampleResponseError401:
    properties:
      message:
        example: Invalid Credentials
        type: string
      status:
        example: error
        type: string
      statusCode:
        example: 401
        type: integer
    type: object
  handlers.loginSampleResponseError500:
    properties:
      message:
        example: An error occured
        type: string
      status:
        example: error
        type: string
      statusCode:
        example: 500
        type: integer
    type: object
  handlers.profileSampleResponse200:
    properties:
      message:
        example: Request successful
        type: string
      profile:
        properties:
          bio:
            example: The best FamTrust user of all time.
            type: string
          bvn:
            example: 35473783473
            type: integer
          createdAt:
            example: "2024-07-22T14:30:00Z"
            type: string
          firstName:
            example: Famtrust
            type: string
          id:
            example: a5c9f82e-6b7a-4a53-a81c-82b1e2f453a6
            type: string
          lastName:
            example: Guru
            type: string
          nin:
            example: 35473745433
            type: integer
          profilePictureUrl:
            example: https://image.famtrust.biz/dkkjieikdjfoej.jpg
            type: string
          updatedAt:
            example: "2024-07-22T14:30:00Z"
            type: string
          userID:
            example: d38f91b2-dc3b-4f9d-aeb4-7b95c91e9d08
            type: string
        type: object
      status:
        example: success
        type: string
      statusCode:
        example: 200
        type: integer
      token:
        example: b6d4a7e1d2d841a1afe874a2a5c15d8b
        type: string
    type: object
  handlers.validateSampleResponse200:
    properties:
      data:
        properties:
          user:
            $ref: '#/definitions/handlers.validateSampleResponse200User'
        type: object
      message:
        example: Request successful
        type: string
      status:
        example: success
        type: string
      statusCode:
        example: 200
        type: integer
      token:
        example: b6d4a7e1d2d841a1afe874a2a5c15d8b
        type: string
    type: object
  handlers.validateSampleResponse200User:
    properties:
      email:
        example: user@example.com
        type: string
      has2FA:
        example: true
        type: boolean
      id:
        example: d38f91b2-dc3b-4f9d-aeb4-7b95c91e9d08
        type: string
      isFreezed:
        example: true
        type: boolean
      isVerified:
        example: true
        type: boolean
      lastLogin:
        example: "2024-07-22T14:30:00Z"
        type: string
      role:
        $ref: '#/definitions/handlers.validateSampleResponseRole'
    type: object
  handlers.validateSampleResponseRole:
    properties:
      id:
        example: admin
        type: string
      permissions:
        example:
        - canTransact
        - ' canWithdraw'
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: This is the Authentication and Authorization Micro-service for the
    FamTrust Web App.
  title: FamTrust API Backend - Auth
  version: "1.0"
paths:
  /images/profile-pic/{imageName}:
    get:
      description: Get User Profile Picture
      operationId: get-profile-pic
      parameters:
      - description: Picture Filename
        in: path
        name: imageName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Get User Profile Picture
      tags:
      - User-Profiles
  /login:
    post:
      consumes:
      - application/json
      description: Login to FamTrust (Supports 2FA by Email)
      operationId: login
      parameters:
      - description: User Credentials
        in: body
        name: Credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      - description: User 2FA Code
        in: query
        name: 2FACode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.loginSampleResponse200'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError401'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      summary: Login to FamTrust (Supports 2FA by Email)
      tags:
      - User-Authentication
  /profile:
    get:
      consumes:
      - application/json
      description: Retrieve User Profile Details
      operationId: profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.profileSampleResponse200'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError401'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      security:
      - BearerAuth: []
      summary: Retrieve User Profile Details
      tags:
      - User-Profiles
  /profile/create:
    post:
      consumes:
      - multipart/form-data
      description: Create New User Profile
      operationId: create-profile
      parameters:
      - description: User's first name
        in: formData
        name: firstName
        required: true
        type: string
      - description: User's last name
        in: formData
        name: lastName
        required: true
        type: string
      - description: User's biography
        in: formData
        name: bio
        required: true
        type: string
      - description: User's National Identification Number
        in: formData
        name: nin
        type: integer
      - description: User's Bank Verification Number
        in: formData
        name: bvn
        type: integer
      - description: User's profile picture
        in: formData
        name: profilePicture
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create New User Profile
      tags:
      - User-Profiles
  /profile/update:
    put:
      consumes:
      - multipart/form-data
      description: Update User Profile
      operationId: update-profile
      parameters:
      - description: User's first name
        in: formData
        name: firstName
        type: string
      - description: User's last name
        in: formData
        name: lastName
        type: string
      - description: User's biography
        in: formData
        name: bio
        type: string
      - description: User's National Identification Number
        in: formData
        name: nin
        type: integer
      - description: User's Bank Verification Number
        in: formData
        name: bvn
        type: integer
      - description: User's profile picture
        in: formData
        name: profilePicture
        type: file
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update User Profile
      tags:
      - User-Profiles
  /signup:
    post:
      consumes:
      - multipart/form-data
      description: Create an Admin/Main User Account
      operationId: signup
      parameters:
      - description: Email of the new user
        in: formData
        name: email
        required: true
        type: string
      - description: Password of the new user
        in: formData
        name: password
        required: true
        type: string
      - description: User's default group ID
        in: formData
        name: defaultGroupID
        required: true
        type: string
      - description: Optional true or false value to set new user 2FA preference
        in: formData
        name: has2FA
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      summary: Create an Admin/Main User Account
      tags:
      - User-Accounts
  /users:
    get:
      consumes:
      - application/json
      description: Get All Users in Group - Requires the canListUsers permission
      operationId: all-users-in-group
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      security:
      - BearerAuth: []
      summary: Get All Users in Group
      tags:
      - User-Accounts
    post:
      consumes:
      - multipart/form-data
      description: Create a Sub-User/Member User Account - Requires the canCreateUsers
        permission
      operationId: create-user
      parameters:
      - description: Email of the new user
        in: formData
        name: email
        required: true
        type: string
      - description: Password of the new user
        in: formData
        name: password
        required: true
        type: string
      - description: Optional Role ID string for new user. Defaults to 'member' if
          not specified
        in: formData
        name: roleID
        type: string
      - description: Optional true or false value to set new user 2FA preference
        in: formData
        name: has2FA
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      security:
      - BearerAuth: []
      summary: Create a Sub-User/Member User Account
      tags:
      - User-Accounts
  /users/{userID}:
    get:
      consumes:
      - application/json
      description: Get One User in User's Group - Requires the canListUsers permission
      operationId: one-user-group
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      security:
      - BearerAuth: []
      summary: Get One User
      tags:
      - User-Accounts
  /validate:
    get:
      consumes:
      - application/json
      description: Validate User Login Token
      operationId: validate
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.validateSampleResponse200'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError401'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.loginSampleResponseError500'
      security:
      - BearerAuth: []
      summary: Validate User Login Token
      tags:
      - User-Authentication
  /verify-bvn:
    get:
      description: Verify User Signup BVN - Currently this is any 10 digit positive
        integer not currently in use by another user.
      operationId: verify-bvn
      parameters:
      - description: BVN
        in: query
        name: bvn
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify User Signup BVN
      tags:
      - Verifications
  /verify-email:
    get:
      description: Send User-Email Verification Token
      operationId: send-verify-token
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Send User-Email Verification Token
      tags:
      - Verifications
  /verify-email/verify:
    get:
      description: Verify User Email Address via Token
      operationId: verify-email-token
      parameters:
      - description: Email verification Token
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify User Email Address via Token
      tags:
      - Verifications
  /verify-nin:
    get:
      description: Verify User Signup NIN - Currently this is any 10 digit positive
        integer not currently in use by another user.
      operationId: verify-nin
      parameters:
      - description: NIN
        in: query
        name: nin
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Verify User Signup NIN
      tags:
      - Verifications
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
