basePath: /api/v1/
definitions:
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: This is the Authentication and Authrization micro-service for the FamTrust
    Web App.
  title: FamTrust API Backend - Auth
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login to FamTrust
      operationId: login
      parameters:
      - description: User Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login to FamTrust
      tags:
      - Auth
  /validate:
    get:
      consumes:
      - application/json
      description: Validate User Login Token
      operationId: validate
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Validate User Login Token
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
